### ISSUE TITLE
Title typo

### ISSUE THREAD

**Issue by TechnologyClassroom** [Flamingo-tech/Xiaomi_air_purifier_modchip#3]
Unless there is a spelling I am unfamiliar with, the title of the repo should be `purifier` instead of `puriefier`.

**Comment by Flamingo-tech** [comment]
Thanks, Fixed!

**Comment by TechnologyClassroom** [comment]
Cool project btw!  I do not have the purifier, but I like the concept.  If I need one I will consider this one because of this project.

**Comment by Flamingo-tech** [comment]
Thanks appreciate it 👍!
