### ISSUE TITLE
Latest gerber missing track 3v3

### ISSUE THREAD

**Issue by Trught** [Flamingo-tech/Xiaomi_air_purifier_modchip#4]
At latest gerber "Modchip.zip" and web versinon at flamingo-tech.nl "Modchip.ip" is missing 3v3 track from TP2 and connector to MCU.
Green track missing.
![obrazek](https://user-images.githubusercontent.com/6658874/161545028-35b037d5-cc4c-44ca-afab-bfca7f32f9a2.png)

**Comment by Flamingo-tech** [comment]
Thanks & Fixed

**Comment by Protoncek** [comment]
Oh, man... i ordered (and got) previous version in china (PCBway)... 
i just assembled this board today and since it didn't work i went exploring and noticed that STM doesn't get 3.3V. Luckily i found this post... so now it works like a charm, no no harm done...

Thanks for this project!
