### ISSUE TITLE
REQUEST: NFC paged data details

### ISSUE THREAD

**Issue by narioinc** [Flamingo-tech/Xiaomi_air_purifier_modchip#5]
Hi @Flamingo-tech,

Great project and I definitely appreciate the core ideology of saving resources and reusing/recycling them. such DRMs inhibit the notion of reuse.
Any chance you can add some docs about how folks could WRITE the data to the NFC paged data format. I could see that page 0,1 are reserved for the UUID and Page 3 and 4 being writable/partially-writable. However post the first four pages, I couldn't figure out how the password generated from the python function could be written in the right way to the NFC.

I will be giving your pcb files for a try and sending them tomorrow to a local board manufacturer, but thought of checking out the NFC sticker method and help in creating any automated scripts/apps (android, ios, linux) and share them with you. 

Anyways, 

Great work and keep it up mate !

**Comment by Flamingo-tech** [comment]
Hey @narioinc 

Here you go: [Click](https://github.com/Flamingo-tech/xiaomi-air-purifier-reverse-engineering/tree/main/Filter%20information)
